//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nyntra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressID { get; set; }
        public string ProductName { get; set; }
        public string FullName { get; set; }
        public string Mobile { get; set; }
        public string PinCode { get; set; }
        public string Address1 { get; set; }
        public string Locality { get; set; }
        public string CityOrDistrict { get; set; }
        public string State { get; set; }
    }
}
